Repository Diarkis/diarkis-server-template, pull requests merged in 2024-10, with the labels that each got.

#29 rewrite import in go
  Makefile
  README.md
  init.sh
  src/puffer/gen.sh
  src/puffer/vars.sh
  tools/rewrite_import.go
Labels: enhancement

#37 tools: fix rewrite import. ParseComments mode was not set.
  tools/rewrite_import.go
Labels: bug

#40 build: added ms(mars-stats) to linux build settings.
  src/build/linux-build.yml
Labels: invalid

#41 build: use `go mod edit` instead of `go list -m` because cannot acces…
  src/Makefile
Labels: invalid

#38 tools install windows compatible
  go.mod
  init.sh
  tools/install/main.go
  tools/install/syscall_unix.go
  tools/install/syscall_windows.go
Labels: enhancement
